### PR TITLE
remove linter dependency from Dockerfile

### PR DESCRIPTION
**Pull request by mikaelarguedas**
addresses https://github.com/osrf/docker_images/pull/68#discussion_r134572819

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Is the expectation that users don't build their own packages using these Docker containers?

**Comment by mikaelarguedas** [comment]
Which container are you referring to ? This one was made for demo purposes and should be discarded/removed once we ship containers for users to use so I think there is no need to install one specific linter while we don't install any of the other ones.
For the "official" ones that we may ship in the future, it's a good question, I think that we should either install all common test dependencies or none, but not only flake8.

**Comment by ruffsl** [comment]
I'd keep the list indented, but that's my dockerfile format preference.

**Comment by mikaelarguedas** [comment]
I don't think that single-line commands should be indented, though I agree that the previous list should have been.
I don't feel strongly about it, feel free to push a fix to that branch if you think that an indented list makes more sense here

**Comment by ruffsl** [comment]
I find it easier to investigate multi-line lists when using the github blame feature to track when a package was added or removed. But it's no big.

**Pull request merged**
