### PR TITLE
Update maintainer to point to ros-security mailing list + fix package.xml

### PR DESCRIPTION
**Pull request by mikaelarguedas**

### CODE REVIEW

**Comment by kyrofa** [comment]
(note that we're waiting for #178 to be merged so we can rebase here and get some light tests run).

**Comment by kyrofa** [comment]
@mikaelarguedas given that we're holding off on #178 for a little more investigation, shall we run build farm tests here and land?

**Comment by mikaelarguedas** [comment]
Sure, CI just for `sros2` and `sros2_cmake`

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9787/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5412/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7955/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9650/)

**Comment by mikaelarguedas** [comment]
@ivanpauno apologies this is apparently conflicting with https://github.com/ros2/sros2/pull/177

Hopefully not too big of a pain during your overall commit cleanup of that PR. If it is happy to revert this the time you get it merge.

**Pull request merged**
