### PR TITLE
generate_artifacts verb

### PR DESCRIPTION
**Pull request by mikaelarguedas**
Python implementation of  https://github.com/ros2/sros2/issues/82

Includes commits from https://github.com/ros2/sros2/pull/106 until it is merged.
Only third commit is relevant https://github.com/ros2/sros2/commit/5136c7dad058e9e545779739ae81291d18917b88.

How to test it:

Generate the artifacts for `/talker2` and all the identities in `sample_policy.xml`:
```bash
mkdir -p /tmp/sros2_demo && cd /tmp/sros2_demo
svn checkout https://github.com/ros2/sros2/trunk/sros2/test/policies
ros2 security generate_artifacts -k demo_keys -n /talker2 -p /tmp/sros2_demo/policies/sample_policy.xml
```

Run:
```bash
export ROS_SECURITY_ENABLE=true
export ROS_SECURITY_STRATEGY=Enforce
export ROS_SECURITY_ROOT_DIRECTORY=/tmp/sros2_demo/demo_keys
ros2 run demo_nodes_py listener &
ros2 run demo_nodes_cpp talker
```

killing the talker and running the following should also work:
```bash
ros2 run demo_nodes_cpp talker __node:=talker2
```

this should fail:
```bash
ros2 run demo_nodes_cpp talker __node:=talker3
```

The sros2 tutorial should still work as well

### CODE REVIEW

**Comment by mjcarroll** [comment]
Tested locally :+1:, but haven't reviewed the code yet.

**Comment by mjcarroll** [comment]
Will also cover #106:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/6604/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2938/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/5421/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/6429/)

**Comment by mikaelarguedas** [comment]
thanks @mjcarroll for the express reviews! :100: :bowing_man: 

If you merge this and close #106, can you please "Create a merge commit" rather than "Squash and merge" to keep the commits separated?

Thanks!

**Comment by mjcarroll** [comment]
Helps that you were at the top of the inbox this morning.  Will do after @ross-desmond gets a chance to comment on #106 (but I'm not anticipating any issues)

**Pull request merged**
