### PR TITLE
Change rmw_connext_cpp -> rmw_connextdds.

### PR DESCRIPTION
**Pull request by clalancette**
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

### CODE REVIEW

**Review by ivanpauno — APPROVED** [review]

**Comment by ivanpauno** [comment]
should be merged after https://github.com/ros2/ros2/pull/1116

**Review by asorbini — APPROVED** [review]
LGTM as a follow up to #253

**Comment by clalancette** [comment]
@SidFaber @mikaelarguedas A second review here would be appreciated (it is only changes to the documentation, so should be minor).  Thanks in advance.

**Comment by clalancette** [comment]
CI for this was in https://github.com/ros2/rmw_connextdds/issues/9#issuecomment-805863900 (the yellow builds were because of an uncrustify failure in rclcpp that has since been fixed).  So I'll go ahead and merge this, thanks everyone for the reviews.

**Pull request merged**
