### PR TITLE
[TESTS] Update tests and add test for generate_artifacts

### PR DESCRIPTION
**Pull request by mikaelarguedas**
- add some TODOs in the code
- update tests to use tmp_path(_factory) instead of tmp_dir(_factory) reducing pathlib boilerplate
- remove setup.py from coverage report
- add testing for some error conditions
- add high level testing for the generate_artifacts verb

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21045/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15346/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21741/)

**Review by fujitatomoya — APPROVED** [review]
lgtm with green CI.

i do not have maintenance permission for this repo, but i did review the code so posting lgtm.

**Comment by mikaelarguedas** [comment]
> i do not have maintenance permission for this repo, but i did review the code so posting lgtm.

Thanks @fujitatomoya for the review!

@ruffsl @artivis @florcabral ok for you ?

**Review by artivis — APPROVED** [review]
lgtm

**Comment by florcabral** [comment]
LGTM as well :+1:

**Review by florcabral — APPROVED** [review]
LGTM as well 👍

**Comment by mikaelarguedas** [comment]
Thanks!

**Comment by mikaelarguedas** [comment]
@Mergifyio backport jazzy

**Pull request merged**
