### PR TITLE
remove deprecated create_key and list_keys verbs

### PR DESCRIPTION
**Pull request by mikaelarguedas**
Deprecated since 2020

### CODE REVIEW

**Review by ahcorde — APPROVED** [review]

**Comment by clalancette** [comment]
These kinds of changes need to go through a CI round in order to get merged into Rolling, as per our [Contributor guidelines](http://docs.ros.org/en/jazzy/The-ROS2-Project/Contributing/Developer-Guide.html#developer-workflow).  

Please make sure to run CI on these changes, and for any future PRs.

**Comment by mikaelarguedas** [comment]
Oh my bad I assumed that the approval from @ahcorde was enough (as there is no instance of these verbs in the entire codebase).

will do in the future :+1:

We agree that that doesnt apply to PRs for local CI purposes like my ongoing github actions and codecov PRs?

**Comment by clalancette** [comment]
> We agree that that doesnt apply to PRs for local CI purposes like my ongoing github actions and codecov PRs?

Yeah, those are totally fine; they don't affect the code directly.

**Comment by mikaelarguedas** [comment]
> Yeah, those are totally fine; they don't affect the code directly.

Neither does removing verbs that were never used anywhere in the ros2.repos file :thinking:

**Comment by clalancette** [comment]
> Neither does removing verbs that were never used anywhere in the ros2.repos file 🤔

Nevertheless, it is our development practice to always run CI on code changes.  There have been very many times when a change that should not have changed anything broke on Windows.

**Comment by mikaelarguedas** [comment]
ok :+1:

Which jobs should be ran in debug mode ?


 I dont see it in the developper workflow and from my recollection that's where most of my python change headaches came from (Python + Debug + Windows)

**Comment by mikaelarguedas** [comment]
(not trying to be sassy, just wanting to make sure I follow the right workflow for https://github.com/ros2/sros2/pull/300 and future ones)

**Comment by clalancette** [comment]
> Which jobs should be ran in debug mode ?

Yeah, it's a good question.  The honest answer is that we don't (typically) run Windows Debug as part of normal CI.  We usually just wait for the nightlies to run it, and then fixup afterwards.

In any case, it looks like you've figure out how to run it, so that is a nice bonus.  Thanks for doing that.

**Pull request merged**
