### PR TITLE
raise FileNotFoundError if provided permission file doesn't exist

### LINKED ISSUE #41: ros2 security create_permission should abort when a policy file does not exist
## Bug report

**Required Info:**

- Operating System:
  - Windows 10
- Installation type:
  - binaries
- Version or commit hash:
  - Ardent patch 2
- DDS implementation:
  -  Fast-RTPS
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue

```
md C:\dev\ros2\sros2_demo
cd C:\dev\ros2\sros2_demo
ros2 security create_keystore demo_keys
ros2 security create_key demo_keys talker
ros2 security create_permission demo_keys talker this_policy_file_does_not_exist.yaml
```

#### Expected behavior
ros2 security create_permission should refuse to continue if the policy file does not exist.

#### Actual behavior
The policy file is overwritten with permissions that allow everything. stdout from the command is indistinguishable from a run with a real policy file

### PR DESCRIPTION
**Pull request by mikaelarguedas**
Fixes #41

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Is the `FileNotFoundError` exception beind handled by the caller? If not this might result in a stacktrace for the user. On the verb side re-raising this as a `RuntimeError` might be better user experience as it only prints the error message but not a stacktrace.

**Comment by mikaelarguedas** [comment]
It is currently not being handled at the higher level.
I'll just raise a `RuntimeError` with a more detail error message here to keep the change minimal

**Comment by dirk-thomas** [comment]
Since the modules in the `api` directory are supposed to be reused the more specific exception might be better...

**Comment by mikaelarguedas** [comment]
thanks @dirk-thomas for the reviews!

**Pull request merged**
