### PR TITLE
install/setup.bat -> local_setup.bat

### PR DESCRIPTION
**Pull request by sloretz**
install/setup.bat does not exist

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
Yeah that's a tricky one, the presence or not of the install folder depends if you build from source or installed from binaries...

But both `local_setup.bat` and `setup.bat` should be present. I'm surprised it;s not the case for you

**Comment by sloretz** [comment]
`setup.bat` exists, but there's no `install` folder. What's the difference between `setup.bat` and `local_setup.bat` anyways?

**Comment by mikaelarguedas** [comment]
`setup.bat` will source underlay workspaces while `local_setup.bat` sources only this workspace

Not sure what's the best way foarwrd is on this one, looks a bit too much to have to make a different case to specify how to source a workspace if building from source or binaries... But I don;t see a better alternative

**Comment by sloretz** [comment]
I think I misunderstood what `install/setup.bat` meant. How about `<path_to_ros2_install>/setup.bat` ?

**Comment by mikaelarguedas** [comment]
sounds good to me

**Pull request merged**
